### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Jdools05** [Jdools05/ChessGameAI#1]
`Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at xyz.jdools05.ChessGameAI.Population.setBestAgent(Population.java:68)
	at xyz.jdools05.ChessGameAI.Population.naturalSelection(Population.java:97)
	at xyz.jdools05.ChessGameAI.Main.main(Main.java:30)`

This is thrown because the Agents in the species get deleted somehow. 
(This is my first issue ever opened! Did i do it right?)

**Comment by Molkars** [comment]
What is the expected behavior vs what is it doing now

**Comment by Jdools05** [comment]
Well, it shouldn't throw this error and there should be at least one Agent stored in the Species.

**Comment by Molkars** [comment]
There ya go
________________________________
